modLoader = "javafml"
loaderVersion = "[4,)"
license = "GPL3 / CC BY-NC-ND 4.0"

[[mods]]
modId = "tacz"
version = "${file.jarVersion}"
displayName = "Timeless & Classics Guns: Zero"
logoFile = "logo.png"
authors = "Serene Wave Studio | Timeless Squad"
description = '''
'''

# ================= Mixin 配置 =================
[[mixins]]
config = "tacz.mixins.json"

[[mixins]]
config = "tacz.compat.acceleratedrendering.mixins.json"

# ================= 依赖 =================
[[dependencies.tacz]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tacz]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tacz]]
modId = "shouldersurfing"
type = "optional"
versionRange = "[1.21.1-5.0.0,)"
ordering = "NONE"
side = "CLIENT"

[modproperties.tacz]
catalogueItemIcon = "tacz:gun_smith_table"
